const URL_API = "http://localhost:3333";
const LOCALSTORAGE_KEY_TOKEN = "key-token-app_traning";
const LOCALSTORAGE_KEY_THEME = "key-theme-app_traning";

const CLASS_MODALITY_SYSTEM = "CLASS";
const TRAINING_MODALITY_SYSTEM = "TRAINING";

const CLASS_MODALITY_PT = "AULA";
const TRAINING_MODALITY_PT = "TREINO";

export {
  URL_API,
  LOCALSTORAGE_KEY_TOKEN,
  LOCALSTORAGE_KEY_THEME,
  CLASS_MODALITY_SYSTEM,
  TRAINING_MODALITY_SYSTEM,
  CLASS_MODALITY_PT,
  TRAINING_MODALITY_PT,
};
