const LOCAL_STORAGE_TOKEN_NAME = "token_user";
const LOCAL_STORAGE_USER_AUTH_NAME = "auth_user";
const LOCAL_STORAGE_USER_PROFILES_NAME = "profiles_user";
const API_BASE_URL = "http://10.76.64.205:3333";
// const API_BASE_URL = "http://192.168.15.10:3333";

export {
  LOCAL_STORAGE_TOKEN_NAME,
  LOCAL_STORAGE_USER_AUTH_NAME,
  LOCAL_STORAGE_USER_PROFILES_NAME,
  API_BASE_URL,
};
